import { Head, router } from '@inertiajs/react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
type RequestItem = { id: number; title: string; description: string; priority: string; status: string; resolved_at: string | null; unit?: { number: string }; reporter?: { name: string }; assignee?: { name: string } };
type Props = { requests: RequestItem[]; branches: { id: number; name: string }[]; units: { id: number; number: string; branch_id: number }[] };
export default function Maintenance({ requests, branches, units }: Props) {
    const [form, setForm] = useState({ branch_id: String(branches[0]?.id ?? ''), unit_id: '', title: '', description: '', priority: 'medium' });
    return <><Head title="Maintenance requests" /><div className="space-y-5 p-6"><div><h1 className="text-2xl font-semibold">Maintenance requests</h1><p className="text-sm text-muted-foreground">Log issues, assign maintenance, and track resolution time.</p></div><form className="grid gap-2 rounded-xl border p-4 md:grid-cols-4" onSubmit={(event) => { event.preventDefault(); router.post('/maintenance', form); }}><input className="h-9 rounded border px-2" placeholder="Issue title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><select className="h-9 rounded border px-2" value={form.branch_id} onChange={(e) => setForm({ ...form, branch_id: e.target.value })}>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><select className="h-9 rounded border px-2" value={form.unit_id} onChange={(e) => setForm({ ...form, unit_id: e.target.value })}><option value="">No unit</option>{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.number}</option>)}</select><select className="h-9 rounded border px-2" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}>{['low', 'medium', 'high', 'urgent'].map((priority) => <option key={priority}>{priority}</option>)}</select><textarea className="rounded border p-2 md:col-span-3" placeholder="Describe the issue" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><Button type="submit">Log issue</Button></form><div className="space-y-2">{requests.map((item) => <article className="rounded-xl border p-4" key={item.id}><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-medium">{item.title}</h2><p className="text-sm text-muted-foreground">{item.unit?.number ?? 'General'} · Reported by {item.reporter?.name}</p></div><span className="text-sm capitalize">{item.priority} · {item.status}</span></div><p className="mt-2 text-sm">{item.description}</p><div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground">Assigned: {item.assignee?.name ?? 'Maintenance team'} {item.resolved_at ? ` · Resolved ${item.resolved_at}` : ''}<select className="ml-auto rounded border px-2 py-1" value={item.status} onChange={(e) => router.put(`/maintenance/${item.id}`, { status: e.target.value })}>{['open', 'in_progress', 'resolved'].map((status) => <option key={status}>{status}</option>)}</select></div></article>)}</div></div></>;
}
Maintenance.layout = { breadcrumbs: [{ title: 'Maintenance requests', href: '/maintenance' }] };
