[program:hospitality-horizon]
process_name=%(program_name)s
command=php /var/www/hospitality-app/artisan horizon
directory=/var/www/hospitality-app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/hospitality-horizon.log
stopwaitsecs=3600
