import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

type Customer = { id: number; name: string; email: string | null; phone: string | null; nationality: string | null; vip_level: string; loyalty_points: number; notes: string | null; tags: string[] | null; blacklisted: boolean; documents: { label: string; path: string }[] | null };
type Props = { customer: Customer; bookingHistory: { id: number; date: string; amount: number; status: string }[]; totalSpent: number; duplicates: { id: number; name: string; email: string | null; phone: string | null }[] };
export default function CustomerProfile({ customer, bookingHistory, totalSpent, duplicates }: Props) {
    const [label, setLabel] = useState('ID document'); const [document, setDocument] = useState<File | null>(null); const [sourceId, setSourceId] = useState('');
    const upload = () => { if (document) router.post(`/customers/${customer.id}/documents`, { document, label }, { forceFormData: true }); };
    const merge = () => sourceId && window.confirm('Merge this duplicate into the current customer?') && router.post(`/customers/${customer.id}/merge`, { source_id: Number(sourceId) });
    return <><Head title={customer.name} /><div className="space-y-6 p-4"><Link href="/customers" className="text-sm underline">Back to customers</Link><div><h1 className="text-2xl font-semibold">{customer.name}</h1><p className="text-muted-foreground">{customer.email ?? '-'} · {customer.phone ?? '-'}</p></div>
        <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border p-4"><div className="text-sm text-muted-foreground">VIP level</div><strong className="capitalize">{customer.vip_level}</strong></div><div className="rounded-xl border p-4"><div className="text-sm text-muted-foreground">Loyalty points</div><strong>{customer.loyalty_points}</strong></div><div className="rounded-xl border p-4"><div className="text-sm text-muted-foreground">Total spent</div><strong>{totalSpent}</strong></div></div>
        <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border p-4"><h2 className="mb-3 font-medium">Booking history</h2>{bookingHistory.length ? bookingHistory.map((booking) => <div key={booking.id} className="border-t py-2">{booking.date} · {booking.amount} · {booking.status}</div>) : <p className="text-sm text-muted-foreground">No bookings recorded yet.</p>}</section><section className="space-y-3 rounded-xl border p-4"><h2 className="font-medium">Notes and tags</h2><p className="whitespace-pre-wrap text-sm">{customer.notes || 'No notes.'}</p><div className="flex flex-wrap gap-2">{(customer.tags ?? []).map((tag) => <span key={tag} className="rounded bg-muted px-2 py-1 text-xs">{tag}</span>)}</div></section></div>
        <section className="space-y-3 rounded-xl border p-4"><h2 className="font-medium">ID documents</h2>{(customer.documents ?? []).map((doc) => <div key={doc.path} className="text-sm">{doc.label}: {doc.path}</div>)}<div className="flex flex-wrap gap-2"><Input value={label} onChange={(e) => setLabel(e.target.value)} placeholder="Document label" /><Input type="file" accept="image/*" onChange={(e) => setDocument(e.target.files?.[0] ?? null)} /><Button onClick={upload} disabled={!document}>Upload to S3</Button></div></section>
        {duplicates.length > 0 && <section className="space-y-3 rounded-xl border p-4"><h2 className="font-medium">Possible duplicate records</h2><select className="h-9 rounded-md border px-2" value={sourceId} onChange={(e) => setSourceId(e.target.value)}><option value="">Select a duplicate</option>{duplicates.map((duplicate) => <option key={duplicate.id} value={duplicate.id}>{duplicate.name} · {duplicate.email ?? duplicate.phone}</option>)}</select><Button variant="outline" onClick={merge} disabled={!sourceId}>Merge into this profile</Button></section>}</div></>;
}
CustomerProfile.layout = { breadcrumbs: [{ title: 'Customers', href: '/customers' }, { title: 'Profile', href: '#' }] };
