import { Head, router } from '@inertiajs/react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';

type Item = { id: number; title: string; priority: string; status: string; due_at: string | null; unit?: { number: string }; employee?: { name: string } };
type Props = { tasks: Item[]; branches: { id: number; name: string }[]; units: { id: number; number: string; branch_id: number }[]; employees: { id: number; name: string }[] };
export default function Tasks({ tasks, branches, units, employees }: Props) {
    const [form, setForm] = useState({ branch_id: String(branches[0]?.id ?? ''), assigned_to: '', unit_id: '', title: '', description: '', priority: 'medium', due_at: '' });
    return <><Head title="Task management" /><div className="space-y-5 p-6"><div><h1 className="text-2xl font-semibold">Task management</h1><p className="text-sm text-muted-foreground">Assign operational tasks to any employee.</p></div><form className="grid gap-2 rounded-xl border p-4 md:grid-cols-4" onSubmit={(event) => { event.preventDefault(); router.post('/tasks', form); }}><input className="h-9 rounded border px-2" placeholder="Task title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><select className="h-9 rounded border px-2" value={form.branch_id} onChange={(e) => setForm({ ...form, branch_id: e.target.value })}>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><select className="h-9 rounded border px-2" value={form.assigned_to} onChange={(e) => setForm({ ...form, assigned_to: e.target.value })}><option value="">Unassigned</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select><select className="h-9 rounded border px-2" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}>{['low', 'medium', 'high', 'urgent'].map((priority) => <option key={priority}>{priority}</option>)}</select><input className="h-9 rounded border px-2" type="datetime-local" value={form.due_at} onChange={(e) => setForm({ ...form, due_at: e.target.value })} /><Button type="submit">Create task</Button></form><div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-muted/40 text-xs uppercase"><tr><th className="p-3">Task</th><th className="p-3">Unit</th><th className="p-3">Assignee</th><th className="p-3">Priority</th><th className="p-3">Status</th></tr></thead><tbody>{tasks.map((task) => <tr className="border-t" key={task.id}><td className="p-3">{task.title}</td><td className="p-3">{task.unit?.number ?? '—'}</td><td className="p-3">{task.employee?.name ?? 'Unassigned'}</td><td className="p-3 capitalize">{task.priority}</td><td className="p-3"><select className="rounded border px-2 py-1" value={task.status} onChange={(e) => router.put(`/tasks/${task.id}`, { status: e.target.value })}>{['pending', 'in_progress', 'done', 'skipped'].map((status) => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div></div></>;
}
Tasks.layout = { breadcrumbs: [{ title: 'Task management', href: '/tasks' }] };
